// WHICH CORPUS THE APP IS LOOKING AT. Every instrument, model and view in this
// repo imports its graph from here and has done since before there was more
// than one; the names and shapes below are exactly what they have always been.
// What changed is that the DATA is no longer written in this file.
//
// Two corpora ship:
//
//   teaching (default)  the hand-authored CS teaching corpus — `teachingdata.ts`.
//                       Six domains, sixteen modules, 53 topics, 116 authored
//                       edges. Every pinned test in the repo measures this one.
//
//   courses             36 real courses from Toronto Metropolitan University's
//                       published Computer Science outlines — `coursedata.ts`,
//                       GENERATED by `tools/courseimport/`. Its "topics" are
//                       courses and its `depends_on` edges are the university's
//                       own published prerequisites. The other three relations
//                       are empty, because institutional data does not publish
//                       them — that absence is a finding, not a gap to fill in.
//
// CHOOSING ONE: `VITE_CORPUS=courses npm run dev`, or the same variable in front
// of `npm run build`. Unset means teaching, so every existing script, test and
// screenshot run behaves as before. The switch is BUILD-TIME on purpose: the
// corpus is a module-level constant that forty files import directly, and making
// it swappable while the app is running is a different and much larger change.

import { buildCorpus } from './corpusbuild'
import { COURSES } from './coursedata'
import type { EdgeType, GEdge, GNode } from './graphshape'
import { ROOT_ID } from './graphshape'
import { TEACHING } from './teachingdata'

export type { CorpusSpec, DeepSpec, EdgeType, GEdge, GNode } from './graphshape'
export { ROOT_ID, slug } from './graphshape'

/** which corpus this build is carrying — read by `docs.ts` and `walks.ts` so all
 *  three make the same choice, and by anything that wants to say so on screen */
// `import.meta.env` is Vite's, and is simply absent under plain node — the cast
// is what lets this file typecheck in both places without pulling vite/client
// types into the app's tsconfig. Same reasoning as `src/platform/index.ts`.
const buildEnv = (import.meta as unknown as { env?: Record<string, string | undefined> }).env
export const CORPUS_NAME: 'teaching' | 'courses' = buildEnv?.VITE_CORPUS === 'courses' ? 'courses' : 'teaching'

// ── Palette ──────────────────────────────────────────────────────────────────
// THERE IS NO DOMAIN COLOUR TABLE (DS OB-153, 2026-09-14). Six authored hexes
// lived here until then. The owner's ruling: the topics are not fixed — this is a
// general graphing tool and a topic is whatever the user makes — so a six-entry
// table was the wrong shape whatever its values. A top-level topic is handed a
// RING HUE NAME by creation order (`src/model/topichue.ts`), the name is stored on
// the node (`GNode.hue`, below on each domain's declaration), and every drawing
// resolves it through `topicPaint()` / `topicPaintValues()`. The demo graph ships
// with its six slots already saved — one graph's stored state, the same kind a
// user's graph carries — chosen to sit near the old look: leaf, violet, iris,
// river, amber, fern. Delete this corpus and no topic-colour logic is left behind.
//
// Edge types take three hues + neutral gray, kept hue-disjoint from the ring's
// first eight topics by the walk (`TOPIC_WALK`): an edge colour can never be
// misread as a topic colour. `depends_on` is the most common type, so it gets the
// gray: the prerequisite backbone recedes, rarer semantic links pop.

// THE NATURALISED COLUMN, NOT THE RAW ONE (OB-123). Until 2026-09-03 these were
// full-saturation orange, red and hot pink drawn over paper pastels, while every
// fill, label and walk hairline around them had already been naturalised — so the
// relation arrows looked like they belonged to a different drawing, because they
// did. `tokens/colors.css` states the rule they were breaching: a view converts its
// swatches and its strokes together or not at all. Every legend swatch in the app
// reads this same table, so they move together.
//
// The five values mirror `--edge-*` in `src/tokens/colors.css` exactly, and
// `edgecolor.test.ts` reads that file and asserts they still agree. That test is the
// point: a hand-kept mirror going stale unnoticed is precisely how
// `--color-edge-mixed` sat a generation behind in `tokens/kn-theme.css`.
//
// WHY NOT `var(--edge-uses)` DIRECTLY: these strings are handed to SVG `stroke` and
// `fill` PRESENTATION ATTRIBUTES, where a `var()` does not resolve — it is not a
// parse error, the attribute is simply dropped and the shape renders black. Same
// constraint that makes `src/model/color.ts` compute its own oklch values rather
// than reading the tokens.
export const EDGE_COLOR: Record<EdgeType, string> = {
  // --edge-depends-on. Deliberately NOT a ring hue: the prerequisite backbone is the
  // common case, and the common case recedes.
  depends_on: '#ada291',
  uses: 'oklch(0.6 0.14 42)', // --edge-uses, via --hue-clay-stroke
  see_also: 'oklch(0.6 0.14 322)', // --edge-see-also, via --hue-mallow-stroke
  implemented_with: 'oklch(0.6 0.14 20)', // --edge-implemented-with, via --hue-brick-stroke
}
// --edge-mixed: an aggregate of several types, deliberately not a 17th ring hue.
export const MIXED_EDGE_COLOR = 'oklch(0.52 0.035 255)'

export const EDGE_LABEL: Record<EdgeType, string> = {
  depends_on: 'builds on',
  uses: 'uses',
  see_also: 'see also',
  implemented_with: 'implemented with',
}

// ── Built ───────────────────────────────────────────────────────────────────
// One call turns the chosen corpus's authored tree, deep layers and edge list
// into the finished graph. Every name below is one the app has imported since
// before there was a second dataset, and the shapes are unchanged.
const built = buildCorpus(CORPUS_NAME === 'courses' ? COURSES : TEACHING, ROOT_ID)

export const nodes: GNode[] = built.nodes
export const edges: GEdge[] = built.edges
export const byId = built.byId
export const childrenOf = built.childrenOf
export const DEEP_DOC = built.deepDoc
export const allContainerIds = built.allContainerIds
/** the edge-bearing topics, in authoring order (the graph views' node set) */
export const topicIds = built.topicIds
export const domainIds = built.domainIds
export const MAX_DEPTH = built.maxDepth
export const isTopic = built.isTopic
export const pathTo = built.pathTo
export const domainOf = built.domainOf
export const topicHueOf = built.topicHueOf
export const topicsUnder = built.topicsUnder
export const depthOf = built.depthOf
